### ISSUE TITLE
Requesting a Nudge

### ISSUE THREAD

**Issue by j0wns** [segfly/carlinkit-modding#1]
I've also wanted to update my CarlinKit and managed to get myself stuck in a similar way.
I upgraded from 2020.08.27.1759 to 2021.03.10.1430 now the device connects shows a grey screen with a QR code and the WiFi details.
It will not proceed with CarPlay configuration.
Subsequent attempts to upgrade or downgrade are not accepted by the device (no green/red blinking) and combing community discussions led me here..

Do you think I'm at a position where I need to get equipment to flash the device manually?
If you had to do it all over again, what firmware would you target as a destination?
At this point, I'd just like to get the device working again.
I'm even OK with stock firmware for now.

`{"version":"2020.08.27.1759","type":"IU","boxMac":"44:01:bb:XX:XX:XX","fileName":"U2W_ZYD_Update.img"}`
`{"version":"2021.03.10.1430","type":"JU","boxMac":"00:e0:4c:XX:XX:XX","fileName":"U2W_ZYD_Update.img"}`

**Comment by segfly** [comment]
Hi @j0wns,

Sorry, but it sounds like you may have bricked the device. It's _very_ easy to do because the device's onboard update process is a poorly-written shell script that unpacks the img file contents and copies over individual files in the root partition. The script is not very smart and does-not/can-not revert certain files when rolling back, as they may have been overwritten by an update and the older img files don't contain the original file.

Before you do anything else, I suggest [dumping the flash](https://github.com/segfly/carlinkit-modding#restoring-the-device) like I did. In particular, you want to save the `/etc/uuid_sign` file because this file is important to keep the activation.

You'll need to carefully read through the https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering repo in order to find the right img file for your device. For my device, `2020.11.10.2138_ROLLBACK` was the latest version I could use given I needed to be able to SSH into the device to make the changes and enable WPA2.

The exact img file you need may be different - but in general, the `ROLLBACK` versions are more likely to be able to restore a broken device because they seem to contain more (but not all) of the older files prior to later img updates.

However there are some cases where once a file is replaced/changed by an update, there's no going back. I consider myself very lucky I was able to recover the device. I should have dumped the flash before doing any updates.

Hope that helps, and good luck!
